[workspace]
resolver = "3"
members = ["kernel"]

[package]
name = "freeworldos-builder"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
m1-ci-self-test = ["kernel/m1-ci-self-test"]
m3-ci-self-test = ["kernel/m3-ci-self-test"]
m35a-ci-self-test = ["kernel/m35a-ci-self-test"]
m35b-ci-self-test = ["kernel/m35b-ci-self-test"]
m35b-ci-panic-test = ["kernel/m35b-ci-panic-test"]
m35b-ci-fatal-test = ["kernel/m35b-ci-fatal-test"]
m35c-ci-self-test = ["kernel/m35c-ci-self-test"]
m35c-ci-guard-fault-test = ["kernel/m35c-ci-guard-fault-test"]
m35c2b-ci-self-test = ["kernel/m35c2b-ci-self-test"]
m35c2c-ci-switch-test = ["kernel/m35c2c-ci-switch-test"]
m35c2d-ci-roundtrip-test = ["kernel/m35c2d-ci-roundtrip-test"]

[dependencies]
ovmf-prebuilt = "=0.2.9"

[build-dependencies]
kernel = { package = "freeworld-kernel", path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = "=0.11.17"
