[package]
name = "freeworld-kernel"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "kernel"
path = "src/main.rs"

[features]
default = []
m1-ci-self-test = []
m3-ci-self-test = []

[dependencies]
bootloader_api = "=0.11.17"
lazy_static = { version = "=1.5.0", features = ["spin_no_std"] }
x86_64 = { version = "=0.15.5", features = ["abi_x86_interrupt"] }
