[package]
name = "freeworld-kernel"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "kernel"
path = "src/main.rs"

[features]
default = []
m1-ci-self-test = []
m3-ci-self-test = []
m35a-ci-self-test = []
m35b-ci-self-test = []
m35b-ci-panic-test = []
m35b-ci-fatal-test = []
m35c-ci-self-test = []
m35c-ci-guard-fault-test = []
m35c2b-ci-self-test = []
m35c2c-ci-switch-test = []
m35c2d-ci-roundtrip-test = []
m35c2e-ci-irq-stack-test = []
m35c2f-ci-trap-frame-test = []
m35c2g-ci-resume-interrupt-test = []
m35c2i-ci-preempt-test = []
m35c2j-ci-run-queue-test = []
m4a-ci-self-test = []
m4b-ci-self-test = []
m4c-ci-self-test = ["m4b-ci-self-test"]
m4d-ci-self-test = ["m4c-ci-self-test"]
m4e-ci-self-test = ["m4d-ci-self-test"]
m5a-ci-self-test = []
m5b-ci-self-test = ["m5a-ci-self-test"]
m5c-ci-self-test = ["m5b-ci-self-test"]
m5d-ci-self-test = ["m5c-ci-self-test"]
m5e-ci-self-test = ["m5d-ci-self-test"]

[dependencies]
bootloader_api = "=0.11.17"
lazy_static = { version = "=1.5.0", features = ["spin_no_std"] }
x86_64 = { version = "=0.15.5", features = ["abi_x86_interrupt"] }
